language: node_js
dist: trusty
sudo: required
env:
  - ETHWS=ws://138.197.179.88:8546
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm run test
